MAP_UNUSED_VOCAB_TO_GENERIC = {'[unused63]': 'gen_entset_down',
                                '[unused64]': 'gen_entset_up',
                                '[unused65]': 'gen_litset',
                                '[unused66]': 'gen_entset_equal',
                                '[unused67]': 'gen_entset_atleast',
                                '[unused68]': 'gen_entset_less',
                                '[unused69]': 'gen_entset_atmost',
                                '[unused70]': 'gen_entset_more',
                                '[unused71]': 'count_litset',
                                '[unused72]': 'count_entset',
                                '[unused73]': 'maximum_litset',
                                '[unused74]': 'minimum_litset',
                                '[unused75]': 'average_litset',
                                '[unused76]': 'intersect_entsets',
                                '[unused77]': 'intersect_litsets',
                                '[unused78]': 'union_entsets',
                                '[unused79]': 'union_litsets',
                                '[unused80]': '<exe>',
                                '[unused91]': '<r1>',
                                '[unused92]': '<r2>',
                                '[unused93]': '<r3>',
                                '[unused94]': '<r4>',
                                '[unused95]': '<r5>',
                                '[unused96]': '<r6>',
                                '[unused97]': '<r7>',
                                '[unused98]': '<r8>',
                                '[unused99]': '<r9>',
                                '[unused100]': '<r10>',
                                '[unused101]': '<r11>',
                                '[unused102]': '<r12>',
                                '[unused103]': 'concat_litsets',
                                }
ALL_RELATIONS = ['/admission_location',
                '/admission_type',
                '/admittime',
                '/admityear',
                '/age',
                '/category',
                '/charttime',
                '/days_stay',
                '/diagnoses_icd9_code',
                '/diagnoses_long_title',
                '/diagnoses_short_title',
                '/diagnoses',
                '/diagnosis',
                '/discharge_location',
                '/dischtime',
                '/dob_year',
                '/dob',
                '/dod_year',
                '/dod',
                '/drug_dose',
                '/drug_type',
                '/drug',
                '/ethnicity',
                '/expire_flag',
                '/flag',
                '/fluid',
                '/formulary_drug_cd',
                '/gender',
                '/hadm_id',
                '/icustay_id',
                '/insurance',
                '/itemid',
                '/label',
                '/lab',
                '/language',
                '/marital_status',
                '/name',
                '/prescriptions',
                '/procedures_icd9_code',
                '/procedures_long_title',
                '/procedures_short_title',
                '/procedures',
                '/religion',
                '/route',
                '/value_unit']